### ISSUE TITLE
Set Manuel's laptop environment 

### ISSUE THREAD

**Issue by mgomezjimenez** [mgomezjimenez/stars_pairs#3]
- [x]  Homebrew
- [ ] Pyenv
- [x] Git
- [x] Python helper tools: pyflakes, pep8, pip.
- [x] PyCharm

**Comment by jdnavarro** [comment]
Let's try doing this first.

**Comment by mgomezjimenez** [comment]
Good, good. I'm checking the Python version I have installed on my laptop, it's the 2.7.10. I don't know how to check other stuff. For example, I use to do the coding on PyCharm, or even directly with gedit, emacs or vi. Any recommendation to do things in a more efficient way?

**Comment by jdnavarro** [comment]
I'd start first with making sure you have a decent package manager properly set so that you can easily and safely install and uninstall any tools you might want to try. In MacOS you could go with [Homebrew](https://brew.sh/).

**Comment by mgomezjimenez** [comment]
Good, Homebrew installed. Do you want me to install Pyenv, Git, Pyflakes, pep8, pip and PyCharm from Brew?
